name: EMAIL

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: |
        echo Hello, world!
        echo ${{ secrets.EMAIL_USERNAME }}
        echo ${{ secrets.EMAIL_PASSWORD }}

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: arcgrg97@gmail.com, naveenmishra1197@gmail.com
          # from email name
          from: Archit Garg
